version: "3.8"
volumes:
  php-fpm-socket:
  db-store:
    driver: local
    driver_opts:
      type: none
      device: $PWD/infra/data
      o: bind
  redis-store:
    driver: local
    driver_opts:
      type: none
      device: $PWD/infra/redis
      o: bind
  psysh-store:


networks:
  backend-net:
    driver: bridge
  frontend-net:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: ./infra/docker/backend/php/Dockerfile
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
      - type: volume
        source: psysh-store
        target: /root/.config/psysh
        volume:
          nocopy: true
    environment:
      # - DB_CONNECTION=mysql
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_DATABASE=${DB_DATABASE:-laravel_local}
      - DB_USERNAME=${DB_USERNAME:-phper}
      - DB_PASSWORD=${DB_PASSWORD:-secret}
      - USER_NAME=${UNAME}
      - USER_ID=${UID}
      - GROUP_NAME=${GNAME}
      - GROUP_ID=${GID}
    networks:
      - backend-net
    depends_on:
      - web
      - db
      - redis

  web:
    build:
      context: .
      dockerfile: ./infra/docker/backend/nginx/Dockerfile
    ports:
      - target: 80
        published: ${WEB_PORT:-80}
        protocol: tcp
        mode: host
    volumes:
      - type: volume
        source: php-fpm-socket
        target: /var/run/php-fpm
        volume:
          nocopy: true
      - type: bind
        source: ./backend
        target: /work/backend
    networks:
      - backend-net
    depends_on:
      - db
      - redis

  db:
    build:
      context: .
      dockerfile: ./infra/docker/backend/mysql/Dockerfile
    ports:
      - target: 3306
        published: ${DB_PORT:-3306}
        protocol: tcp
        mode: host
    volumes:
      - ./infra/docker/backend/mysql/initdb.d:/docker-entrypoint-initdb.d
      - type: volume
        source: db-store
        target: /var/lib/mysql
        volume:
          nocopy: true
    environment:
      - MYSQL_DATABASE=${DB_DATABASE:-laravel_local}
      - MYSQL_USER=${DB_USERNAME:-phper}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
      - USER_NAME=${UNAME}
      - USER_ID=${UID}
      - GROUP_NAME=${GNAME}
      - GROUP_ID=${GID}
    networks:
      - backend-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - ${PMA_PORT:-4040}:80
    volumes:
      - ./infra/phpmyadmin/sessions:/sessions
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=${PMA_USER:-phper}
      - PMA_PASSWORD=${PMA_PASS:-secret}
    networks:
      - backend-net
    links:
      - db

  redis:
    image: "redis:alpine"
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: redis-server --appendonly yes
    volumes:
      - "redis-store:/data"
    networks:
      - backend-net
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    volumes:
      - ./infra/redisinsight:/db
    networks:
      - backend-net
    depends_on:
      - redis
  # webpackを使用する場合
  # client:
  #   build:
  #     context: .
  #     dockerfile: ./infra/docker/frontend/php/Dockerfile
  #   ports:
  #     - ${CLIENT_PORT:-8081}:80
  #   volumes:
  #     - ./frontend:/work/frontend
  #   environment:
  #     - USER_NAME=${UNAME}
  #     - USER_ID=${UID}
  #     - GROUP_NAME=${GNAME}
  #     - GROUP_ID=${GID}
  #   networks:
  #     - frontend-net

  # create-react-appを使用する場合
  client:
    build:
      context: .
      dockerfile: ./infra/docker/frontend/node/Dockerfile
    ports:
      - ${CLIENT_PORT:-3000}:3000
    volumes:
      - ./frontend:/work/frontend
    environment:
      - USER_NAME=${UNAME}
      - USER_ID=${UID}
      - GROUP_NAME=${GNAME}
      - GROUP_ID=${GID}
    tty: true
    networks:
      - frontend-net
