# fly.toml file generated for nextjs-laravel-hands-on-hashiudo-backend on 2022-10-30T08:11:25+09:00

app = "nextjs-laravel-hands-on-hashiudo-backend"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  builder = "heroku/buildpacks:20"
  buildpacks = [
    "heroku/php",
    "heroku/procfile@1.0.1",
    "heroku/nodejs",
  ]

[env]
  APP_DEBUG = "false"
  APP_ENV = "production"
  APP_URL = "https://fly.hashiudo.ga"
  DB_CONNECTION = "postgres"
  FRONTEND_URL = "https://vercel.hashiudo.ga"
  LOG_CHANNEL = "errorlog"
  SANCTUM_STATEFUL_DOMAINS = "vercel.hashiudo.ga"
  SESSION_DOMAIN = ".hashiudo.ga"
  SESSION_DRIVER = "cookie"
  SESSION_LIFETIME = 120

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

[[services.ports]]
  force_https = true
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[services.tcp_checks]]
  grace_period = "30s"
  interval = "15s"
  restart_limit = 0
  timeout = "2s"
