version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:7.3-node-browsers
    working_directory: ~/<GitHubのリポジトリ名>/backend
    steps:
      - checkout:
          path: ~/<GitHubのリポジトリ名>
      - run:
          name: directory check 1
          command: |
            pwd
            ls
      - run: sudo composer self-update --1
      - run: composer install -n --prefer-dist
      - run: yarn install --frozen-lockfile
      - run: yarn run dev
      - run:
          name: directory check 2
          command: |
            pwd
            ls
      - run:
          name: php test
          command: vendor/bin/phpunit
