# https://qiita.com/ucan-lab/items/237d2058eb46ab657ae3

name: laravel-git-clone

on:
  pull_request:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Git Clone Project
        run: git clone https://github.com/laravel/laravel.git backend

      - name: Docker Compose Version
        run: docker-compose --version

      - name: Build Docker
        run: docker-compose up -d --build

      - name: PHP Version
        run: docker-compose exec -T web php --version

      - name: Composer Version
        run: docker-compose exec -T web composer --version

      - name: Composer Install
        run: docker-compose exec -T web composer install

      - name: Laravel Version
        run: docker-compose exec -T web php artisan --version

      - name: Laravel Settings
        run: |
          docker-compose exec -T web cp .env.example .env
          docker-compose exec -T web php artisan key:generate

      - name: Laravel Migrate Testing
        run: docker-compose exec -T web php artisan migrate

      - name: Laravel Rollback Testing
        run: docker-compose exec -T web php artisan migrate:refresh --seed

      - name: Laravel Seeding Testing
        run: docker-compose exec -T web php artisan db:seed

      - name: Laravel PHPUnit Testing
        run: docker-compose exec -T web php artisan test
