# fly.toml file generated for nextjs-laravel-hands-on-hashiudo-redis on 2022-11-04T17:07:32+09:00

app = "nextjs-laravel-hands-on-hashiudo-redis"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "flyio/redis:6.2.6"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]

[[mounts]]
  destination = "/data"
  source = "redis_server"

